---

- name: Create directory for node token
  ansible.builtin.file:
    path: /var/lib/rancher/k3s/server
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy node token from control plane
  ansible.builtin.fetch:
    src: /var/lib/rancher/k3s/server/node-token
    dest: /tmp/node-token
    flat: yes
  delegate_to: "{{ groups['control_plane'][0] }}"
  run_once: true

- name: Copy node token to worker
  ansible.builtin.copy:
    src: /tmp/node-token
    dest: /var/lib/rancher/k3s/server/node-token
    owner: root
    group: root
    mode: '0644'

- name: Copy k3s service file
  ansible.builtin.template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s-node.service"
    owner: root
    group: root
    mode: '0755'

- name: Enable k3s service
  ansible.builtin.systemd:
    name: k3s-node
    daemon_reload: yes
    state: restarted
    enabled: yes
