---
all:
  children:
    control_plane:
      hosts:
        local-kube-101:
          ansible_host: 192.168.56.101
    worker:
      hosts:
        local-kube-102:
          ansible_host: 192.168.56.102
        local-kube-103:
          ansible_host: 192.168.56.103 